from __future__ import annotations

import os
import base64
import logging
import urllib.request
import ssl
import pandas as pd

logger = logging.getLogger(__name__)

_DATATABLES_JS_URL  = "https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"
_JQUERY_URL         = "https://code.jquery.com/jquery-3.7.0.min.js"
_DATATABLES_CSS_URL = "https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>{title}</title>
<style>
{dt_css}
body {{ font-family: Arial, sans-serif; margin: 0; padding: 0;
        background: #f5f5f5; color: #222; }}
header {{ background: #1a3a5c; color: white; padding: 24px 40px; }}
header h1 {{ margin: 0; font-size: 1.8em; }}
header p  {{ margin: 4px 0 0; font-size: 0.95em; opacity: 0.85; }}
main {{ max-width: 1200px; margin: 32px auto; padding: 0 24px; }}
section {{ background: white; border-radius: 8px;
           box-shadow: 0 1px 4px rgba(0,0,0,0.1);
           padding: 28px 32px; margin-bottom: 28px; }}
h2 {{ margin-top: 0; color: #1a3a5c; border-bottom: 2px solid #e0e0e0;
      padding-bottom: 8px; }}
.plot-block {{ margin: 20px 0; text-align: center; }}
.plot-block img {{ max-width: 100%; border: 1px solid #e0e0e0; border-radius: 4px; }}
.plot-caption {{ font-size: 0.9em; color: #555; margin-bottom: 6px; }}
.plot-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
tr.sig-row {{ background-color: #eaf3fb !important; font-weight: bold; }}
a.go-link {{ color: #1a3a5c; text-decoration: underline dotted; cursor: pointer; }}
.col-tip {{ display: inline-block; width: 14px; height: 14px; line-height: 14px;
            font-size: 10px; text-align: center; border-radius: 50%;
            background: #aaa; color: white; cursor: help; margin-left: 3px;
            position: relative; }}
.col-tip .tip-text {{ display: none; position: absolute; bottom: 120%; left: 50%;
                      transform: translateX(-50%); background: #333; color: #fff;
                      padding: 6px 10px; border-radius: 4px; font-size: 11px;
                      white-space: normal; width: 220px; z-index: 999;
                      font-weight: normal; line-height: 1.4; }}
.col-tip:hover .tip-text {{ display: block; }}
thead tr.filter-row th input {{
    width: 100%; box-sizing: border-box; font-size: 11px;
    padding: 3px; border: 1px solid #ccc; border-radius: 3px; }}
thead tr.filter-row th {{ padding: 4px 8px; }}
#modal-overlay {{ display: none; position: fixed; top: 0; left: 0;
                  width: 100%; height: 100%; background: rgba(0,0,0,0.6);
                  z-index: 1000; justify-content: center; align-items: center; }}
#modal-overlay.active {{ display: flex; }}
#modal-box {{ background: white; border-radius: 8px; padding: 24px;
              max-width: 700px; width: 90%; position: relative; }}
#modal-title {{ font-size: 1.1em; font-weight: bold; color: #1a3a5c;
                margin-bottom: 12px; }}
#modal-img {{ width: 100%; border: 1px solid #e0e0e0; border-radius: 4px; }}
#modal-close {{ position: absolute; top: 12px; right: 16px; font-size: 1.4em;
                cursor: pointer; color: #555; background: none; border: none; }}
footer {{ text-align: center; padding: 20px; font-size: 0.85em; color: #888; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>ENHYDRA &mdash; Gene Set Enrichment Analysis for evolutionary genomics</p>
</header>

<div id="modal-overlay">
  <div id="modal-box">
    <button id="modal-close" title="Close">&times;</button>
    <div id="modal-title"></div>
    <img id="modal-img" src="" alt="Enrichment plot"/>
  </div>
</div>

<main>
<section>
  <h2>Plots</h2>
  <div class="plot-grid">
{plots_html}
  </div>
</section>

<section>
  <h2>Enrichment results</h2>
  <p>Significant gene sets are highlighted in blue.
     Click a GO ID to view its enrichment plot.
     Use the filter boxes below each column header to filter by that column.</p>
{table_html}
</section>
</main>
<footer>Generated by ENHYDRA</footer>

<script>{jquery_js}</script>
<script>{dt_js}</script>
<script>
{plot_data_js}
$(document).ready(function() {{
    // Numeric expression filtering for NES, p-value, FDR only
    var numericCols = new Set([2, 3, 4,5,6]);
    var colFilters  = {{}};  // col index → {{ op, num }} or {{ text }}

    $.fn.dataTable.ext.search.push(function(settings, data) {{
        for (var i in colFilters) {{
            var f = colFilters[i];
            if (f.text !== undefined) {{
                if (data[i].toLowerCase().indexOf(f.text) === -1) return false;
            }} else {{
                var cell = parseFloat(data[i]);
                if (isNaN(cell)) return false;
                if (f.op === '<'  && !(cell <  f.num)) return false;
                if (f.op === '<=' && !(cell <= f.num)) return false;
                if (f.op === '>'  && !(cell >  f.num)) return false;
                if (f.op === '>=' && !(cell >= f.num)) return false;
                if ((f.op === '=' || f.op === '==') && !(cell === f.num)) return false;
                if (f.op === '!=' && !(cell !== f.num)) return false;
            }}
        }}
        return true;
    }});

    $('#results-table thead tr.filter-row th').each(function(i) {{
        var placeholder = numericCols.has(i) ? "e.g. < 0.05" : "Filter...";
        var input = $('<input type="text" placeholder="' + placeholder + '"/>');
        $(this).html(input);
        input.on('keyup change', function() {{
            var val = this.value.trim();
            if (val === '') {{
                delete colFilters[i];
            }} else if (numericCols.has(i)) {{
                var m = val.match(/^([<>=!]=?)\s*([\d.eE+\-]+)$/);
                if (m) {{
                    colFilters[i] = {{ op: m[1], num: parseFloat(m[2]) }};
                }} else {{
                    delete colFilters[i];
                }}
            }} else {{
                colFilters[i] = {{ text: val.toLowerCase() }};
            }}
            table.draw();
        }});
    }});
    var table = $('#results-table').DataTable({{
        pageLength: 25,
        orderCellsTop: true,
        order: [[4, 'asc']],
        columnDefs: [{{ targets: [2,3,4,5,6], type: 'num' }}]
    }});
    $(document).on('click', '.go-link', function(e) {{
        e.preventDefault();
        var goId = $(this).data('goid');
        var uri  = enrichmentPlots[goId];
        if (uri) {{
            $('#modal-title').text(goId);
            $('#modal-img').attr('src', uri);
            $('#modal-overlay').addClass('active');
        }}
    }});
    $('#modal-close, #modal-overlay').on('click', function(e) {{
        if (e.target === this) $('#modal-overlay').removeClass('active');
    }});
}});
</script>
</body>
</html>"""


def _fetch(url: str) -> str:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(
        url, headers={"User-Agent": "Mozilla/5.0 (compatible; ENHYDRA)"}
    )
    with urllib.request.urlopen(req, context=ctx) as r:
        return r.read().decode("utf-8", errors="replace")


def _fetch_cached(url: str, cache_dir: str | None, filename: str) -> str:
    if cache_dir:
        local_path = os.path.join(cache_dir, filename)
        if os.path.isfile(local_path):
            with open(local_path, encoding="utf-8") as fh:
                return fh.read()
    content = _fetch(url)
    if cache_dir:
        os.makedirs(cache_dir, exist_ok=True)
        with open(local_path, "w", encoding="utf-8") as fh:
            fh.write(content)
    return content


def _img_to_base64(img_path: str) -> str:
    with open(img_path, "rb") as fh:
        data = base64.b64encode(fh.read()).decode("utf-8")
    return "data:image/png;base64,%s" % data


def _parse_obo_names(obo_path: str) -> dict[str, str]:
    names = {}
    current_id = None
    current_name = None
    is_obsolete = False
    with open(obo_path) as fh:
        for line in fh:
            line = line.rstrip()
            if line == "[Term]":
                if current_id and not is_obsolete and current_name:
                    names[current_id] = current_name
                current_id = None
                current_name = None
                is_obsolete = False
            elif line.startswith("id: GO:"):
                current_id = line[4:]
            elif line.startswith("name: "):
                current_name = line[6:]
            elif line == "is_obsolete: true":
                is_obsolete = True
    if current_id and not is_obsolete and current_name:
        names[current_id] = current_name
    return names


def _load_gsea_results(results_dir: str) -> pd.DataFrame | None:
    """Load and clean GSEApy prerank results, writing a processed TSV."""
    path = os.path.join(results_dir, "gseapy.gene_set.prerank.report.csv")
    if not os.path.isfile(path):
        logger.warning("GSEA results not found: %s", path)
        return None

    df = pd.read_csv(path)

    # Convert Tag% (e.g. "1/10") to float
    if "Tag %" in df.columns:
        def _tag(v):
            try:
                v = str(v).strip()
                if "/" in v:
                    a, b = v.split("/")
                    return round(float(a) / float(b), 4)
                return round(float(v), 4)
            except Exception:
                return None
        df["Tag %"] = df["Tag %"].apply(_tag)

    # Convert Gene% (e.g. "9.55%") to 0-1 float
    if "Gene %" in df.columns:
        def _gene(v):
            try:
                return round(float(str(v).strip().rstrip("%")) / 100.0, 4)
            except Exception:
                return None
        df["Gene %"] = df["Gene %"].apply(_gene)

    # Write processed intermediate file
    processed_path = os.path.join(results_dir, "gsea_results_processed.tsv")
    df.to_csv(processed_path, sep="\t", index=False)
    logger.info("Processed GSEA results written to: %s", processed_path)

    return df


def _build_enrichment_plot_index(results_dir: str) -> dict[str, str]:
    prerank_dir = os.path.join(results_dir, "prerank")
    if not os.path.isdir(prerank_dir):
        return {}
    index = {}
    for filename in os.listdir(prerank_dir):
        if not filename.endswith(".png"):
            continue
        go_id = filename.replace(".png", "").replace("_", ":", 1)
        png_path = os.path.join(prerank_dir, filename)
        index[go_id] = _img_to_base64(png_path)
    logger.info("Indexed %d enrichment plot(s).", len(index))
    return index


def _results_table_html(
    df: pd.DataFrame,
    obo_names: dict[str, str],
    plot_index: dict[str, str],
    fdr_threshold: float = 0.25,
) -> str:
    df = df.copy()

    if "Term" not in df.columns:
        logger.warning("'Term' column not found in GSEA results.")
        return "<p>No results to display.</p>"

    df["GO Term"] = df["Term"].map(obo_names).fillna(df["Term"])

    for col in ["ES", "NES", "NOM p-val", "FDR q-val", "FWER p-val", "Tag %", "Gene %"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").apply(
                lambda x: "%.4f" % x if pd.notna(x) else ""
            )

    df["Significant"] = df["FDR q-val"].apply(
        lambda x: "✓" if x != "" and float(x) < fdr_threshold else ""
    )

    # (source_col, display_name, tooltip)
    col_defs = [
        ("Term",       "GO ID",
         "Gene Ontology term identifier."),
        ("GO Term",    "Term name",
         "Human-readable name of the GO term."),
        ("NES",        "NES",
         "Normalised Enrichment Score. Positive = enriched at top of ranking "
         "(more conserved). Negative = enriched at bottom (faster evolving)."),
        ("NOM p-val",  "p-value",
         "Nominal p-value from permutation testing. Not corrected for "
         "multiple testing."),
        ("FDR q-val",  "FDR",
         "False Discovery Rate q-value. Gene sets below %.2f are significant."
         % fdr_threshold),
        ("Tag %",      "Tag %",
         "Percentage of genes in the leading edge subset relative to the "
         "total number of genes in the gene set."),
        ("Gene %",     "Gene %",
         "Percentage of genes in the leading edge subset relative to all "
         "genes in the ranked list."),
        ("Significant","Sig.",
         "Significant at FDR < %.2f." % fdr_threshold),
    ]

    col_defs = [(s, d, t) for s, d, t in col_defs
                if s in df.columns or s in ("GO Term", "Significant")]

    table_df = df[[s for s, _, _ in col_defs]].copy()
    display_names = [d for _, d, _ in col_defs]
    tooltips      = [t for _, _, t in col_defs]
    table_df.columns = display_names

    numeric_display_names = {"NES", "p-value", "FDR", "Tag %", "Gene %"}
    numeric_col_indices = [
        i for i, name in enumerate(display_names)
        if name in numeric_display_names
    ]

    header_cells = "".join(
        '<th>%s <span class="col-tip">?<span class="tip-text">%s</span></span></th>'
        % (name, tip)
        for name, tip in zip(display_names, tooltips)
    )
    filter_cells = "<th></th>" * len(display_names)

    rows = ""
    for _, row in table_df.iterrows():
        sig_class = ' class="sig-row"' if row.get("Sig.") == "✓" else ""
        go_id = row.get("GO ID", "")
        has_plot = go_id in plot_index
        cells = ""
        for col, val in row.items():
            if col == "GO ID" and has_plot:
                cells += (
                    '<td><a href="#" class="go-link" data-goid="%s">%s</a></td>'
                    % (go_id, val)
                )
            else:
                cells += "<td>%s</td>" % str(val)
        rows += "<tr%s>%s</tr>\n" % (sig_class, cells)

    return (
        '<table id="results-table" class="display compact" style="width:100%%">'
        "<thead>"
        "<tr>%s</tr>"
        '<tr class="filter-row">%s</tr>'
        "</thead>"
        "<tbody>%s</tbody>"
        "</table>"
    ) % (header_cells, filter_cells, rows), numeric_col_indices


def _plot_section(plots_dir: str, names: list[tuple[str, str]]) -> str:
    html = ""
    for stem, caption in names:
        png_path = os.path.join(plots_dir, stem + ".png")
        if not os.path.isfile(png_path):
            continue
        uri = _img_to_base64(png_path)
        html += (
            '<div class="plot-block">'
            '<p class="plot-caption">%s</p>'
            '<img src="%s" alt="%s"/>'
            "</div>"
        ) % (caption, uri, caption)
    return html


def build_report(
    results_dir: str,
    plots_dir: str,
    report_path: str,
    obo_path: str | None = None,
    mode: str = "single",
    metric: str = "zscore",
    fdr_threshold: float = 0.25,
):
    """Build a self-contained HTML report for ENHYDRA results."""
    logger.info("Building HTML report...")

    obo_names = {}
    if obo_path and os.path.isfile(obo_path):
        obo_names = _parse_obo_names(obo_path)
        logger.info("Loaded %d GO term names from OBO.", len(obo_names))
    else:
        logger.warning("OBO file not provided or not found — term names from GMT only.")

    df = _load_gsea_results(results_dir)
    if df is None:
        logger.warning("Cannot build report: no GSEA results found.")
        return

    cache_dir = os.path.dirname(obo_path) if obo_path else None
    logger.info("Fetching DataTables assets (cached after first download)...")
    jquery_js = _fetch_cached(_JQUERY_URL,         cache_dir, "jquery.min.js")
    dt_js     = _fetch_cached(_DATATABLES_JS_URL,  cache_dir, "datatables.min.js")
    dt_css    = _fetch_cached(_DATATABLES_CSS_URL, cache_dir, "datatables.min.css")

    plot_index = _build_enrichment_plot_index(results_dir)
    plot_data_js = "var enrichmentPlots = {%s};" % ",".join(
        '"%s": "%s"' % (go_id, uri) for go_id, uri in plot_index.items()
    )

    if mode == "single":
        plot_names = [
            ("identity_distribution", "Distribution of mean alignment identity"),
            ("gsea_barplot",          "Top enriched gene sets (NES)"),
        ]
        title = "ENHYDRA Single-List Enrichment Report"
    else:
        plot_names = [
            ("identity_scatter",          "Identity comparison between lists"),
            ("differential_distribution", "Differential conservation score distribution"),
            ("identity_distribution",     "Distribution of differential scores"),
            ("gsea_barplot",              "Top differentially enriched gene sets (NES)"),
        ]
        title = "ENHYDRA Differential Enrichment Report"

    plots_html = _plot_section(plots_dir, plot_names)
    table_html, numeric_col_indices = _results_table_html(
        df, obo_names, plot_index, fdr_threshold
    )

    html = _TEMPLATE.format(
        title=title,
        dt_css=dt_css,
        plots_html=plots_html,
        table_html=table_html,
        jquery_js=jquery_js,
        dt_js=dt_js,
        plot_data_js=plot_data_js,
        numeric_col_indices=numeric_col_indices,
    )

    with open(report_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    logger.info("HTML report written to: %s", report_path)
